sonar.projectKey=fiap-devops-gs1
sonar.projectName=fiap-devops-gs1
sonar.sources=.
sonar.tests=tests
sonar.exclusions=venv/**,.venv/**,tests/**,jenkins-sonar-installation/**,docs/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
